
package com.cybersource.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ITransactionProcessor", targetNamespace = "urn:schemas-cybersource-com:transaction-data:TransactionProcessor")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITransactionProcessor {


    /**
     * 
     * @param input
     * @return
     *     returns com.cybersource.stub.ReplyMessage
     */
    @WebMethod(action = "runTransaction")
    @WebResult(name = "replyMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.219", partName = "result")
    public ReplyMessage runTransaction(
        @WebParam(name = "requestMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.219", partName = "input")
        RequestMessage input);

}
